language: python
sudo: require
python:
  - "3.6"
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

# command to run tests
script:
  - python -m compileall ./
  - coverage run --omit='*/virtualenv/*,*/site-packages/*,*_test.py' -m unittest discover -s . -v -p "*_test.py"

# create coverage for one python version
after_success:
  - test $TRAVIS_PYTHON_VERSION == "3.8" && coveralls

notifications:
  email: false

deploy:
  provider: script
  script: curl https://rico-j.de/travis/deploy-bj.sh
  on:
    branch: master
